name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd app
          npm install

      - name: Run tests
        run: |
          cd app
          npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_test
    if: success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t my-app:${{ github.sha }} ../app -f ./build

      - name: Push Docker image to registry (e.g., Docker Hub)
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push my-app:${{ github.sha }}

      - name: Deploy to Cloud (e.g., AWS ECS)
        run: |
          # AWS CLIを使ってECSにデプロイするコマンドを記述
          # 例: aws ecs update-service --cluster my-cluster --service my-service --force-new-deployment
